---
- name: Provision BGP configuration
  hosts: routers
  roles:
   - Juniper.junos
  connection: local
  gather_facts: no

  vars:
    config_file: configs/{{ inventory_hostname }}.conf
    diffs_file: configs/{{ inventory_hostname }}.diff

  tasks:
   - name: Generate config
     template:
       src: templates/bgp.j2
       dest: "{{ config_file }}"

   - name: Load config on the device
     juniper_junos_config:
       provider: "{{ provider }}"
       load: replace
       commit: true
       src: "{{ config_file }}"
       diffs_file: "{{ diffs_file }}"
     register: result

   - name: Print diff
     debug: var=result.diff_lines
     when: result.diff_lines is defined

   - name: Wait for BGP to come up
     juniper_junos_command:
       provider: "{{ provider }}"
       commands:
        - show bgp summary
       format: json
     register: bgp_state
     until:
       bgp_state.parsed_output["bgp-information"][0]["bgp-peer"][0]
       ["peer-state"][0]["data"]=="Established"
     retries: 20
     delay: 10


