# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cmerror_data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import telemetry_top_pb2 as telemetry__top__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cmerror_data.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x12\x63merror_data.proto\x1a\x13telemetry_top.proto\"\x8d\x03\n\tErrorData\x12\x19\n\nidentifier\x18\x01 \x01(\tB\x05\x82@\x02\x08\x01\x12\x14\n\x05\x63ount\x18\x02 \x01(\x04\x42\x05\x82@\x02\x18\x01\x12\x1b\n\x0clast_updated\x18\x03 \x01(\x04\x42\x05\x82@\x02\x10\x01\x12\x12\n\nis_enabled\x18\x04 \x01(\x08\x12\x11\n\tmodule_id\x18\x05 \x01(\r\x12\x14\n\x0c\x63omponent_id\x18\x06 \x01(\r\x12\x12\n\nerror_code\x18\x07 \x01(\r\x12\x1a\n\x0boccur_count\x18\x08 \x01(\rB\x05\x82@\x02\x18\x01\x12\x1c\n\rcleared_count\x18\t \x01(\rB\x05\x82@\x02\x18\x01\x12\x1e\n\x0flast_cleared_at\x18\n \x01(\x04\x42\x05\x82@\x02\x10\x01\x12\x1b\n\x0c\x61\x63tion_count\x18\x0b \x01(\rB\x05\x82@\x02\x18\x01\x12#\n\x14last_action_taken_at\x18\x0c \x01(\x04\x42\x05\x82@\x02\x10\x01\x12\x10\n\x08\x66ru_type\x18\r \x01(\t\x12\x10\n\x08\x66ru_slot\x18\x0e \x01(\r\x12\x13\n\x0b\x64\x65scription\x18\x0f \x01(\t\x12\x0c\n\x04help\x18\x10 \x01(\t\"<\n\x11\x45rrorResourceInfo\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\r\n\x05state\x18\x03 \x01(\r\"|\n\x0b\x43merrorData\x12\x1e\n\nerror_item\x18\x01 \x03(\x0b\x32\n.ErrorData\x12\x10\n\x08\x66ru_slot\x18\x02 \x01(\r\x12\x10\n\x08\x66ru_type\x18\x03 \x01(\t\x12)\n\rresource_item\x18\x04 \x03(\x0b\x32\x12.ErrorResourceInfo:D\n\x15jnpr_cmerror_data_ext\x12\x17.JuniperNetworksSensors\x18\x15 \x01(\x0b\x32\x0c.CmerrorData')
  ,
  dependencies=[telemetry__top__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


JNPR_CMERROR_DATA_EXT_FIELD_NUMBER = 21
jnpr_cmerror_data_ext = _descriptor.FieldDescriptor(
  name='jnpr_cmerror_data_ext', full_name='jnpr_cmerror_data_ext', index=0,
  number=21, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


_ERRORDATA = _descriptor.Descriptor(
  name='ErrorData',
  full_name='ErrorData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='identifier', full_name='ErrorData.identifier', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\010\001'))),
    _descriptor.FieldDescriptor(
      name='count', full_name='ErrorData.count', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\030\001'))),
    _descriptor.FieldDescriptor(
      name='last_updated', full_name='ErrorData.last_updated', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\020\001'))),
    _descriptor.FieldDescriptor(
      name='is_enabled', full_name='ErrorData.is_enabled', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='module_id', full_name='ErrorData.module_id', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='component_id', full_name='ErrorData.component_id', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='error_code', full_name='ErrorData.error_code', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='occur_count', full_name='ErrorData.occur_count', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\030\001'))),
    _descriptor.FieldDescriptor(
      name='cleared_count', full_name='ErrorData.cleared_count', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\030\001'))),
    _descriptor.FieldDescriptor(
      name='last_cleared_at', full_name='ErrorData.last_cleared_at', index=9,
      number=10, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\020\001'))),
    _descriptor.FieldDescriptor(
      name='action_count', full_name='ErrorData.action_count', index=10,
      number=11, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\030\001'))),
    _descriptor.FieldDescriptor(
      name='last_action_taken_at', full_name='ErrorData.last_action_taken_at', index=11,
      number=12, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\020\001'))),
    _descriptor.FieldDescriptor(
      name='fru_type', full_name='ErrorData.fru_type', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fru_slot', full_name='ErrorData.fru_slot', index=13,
      number=14, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='ErrorData.description', index=14,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='help', full_name='ErrorData.help', index=15,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=441,
)


_ERRORRESOURCEINFO = _descriptor.Descriptor(
  name='ErrorResourceInfo',
  full_name='ErrorResourceInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ErrorResourceInfo.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='ErrorResourceInfo.type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='state', full_name='ErrorResourceInfo.state', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=443,
  serialized_end=503,
)


_CMERRORDATA = _descriptor.Descriptor(
  name='CmerrorData',
  full_name='CmerrorData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error_item', full_name='CmerrorData.error_item', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fru_slot', full_name='CmerrorData.fru_slot', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fru_type', full_name='CmerrorData.fru_type', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='resource_item', full_name='CmerrorData.resource_item', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=505,
  serialized_end=629,
)

_CMERRORDATA.fields_by_name['error_item'].message_type = _ERRORDATA
_CMERRORDATA.fields_by_name['resource_item'].message_type = _ERRORRESOURCEINFO
DESCRIPTOR.message_types_by_name['ErrorData'] = _ERRORDATA
DESCRIPTOR.message_types_by_name['ErrorResourceInfo'] = _ERRORRESOURCEINFO
DESCRIPTOR.message_types_by_name['CmerrorData'] = _CMERRORDATA
DESCRIPTOR.extensions_by_name['jnpr_cmerror_data_ext'] = jnpr_cmerror_data_ext

ErrorData = _reflection.GeneratedProtocolMessageType('ErrorData', (_message.Message,), dict(
  DESCRIPTOR = _ERRORDATA,
  __module__ = 'cmerror_data_pb2'
  # @@protoc_insertion_point(class_scope:ErrorData)
  ))
_sym_db.RegisterMessage(ErrorData)

ErrorResourceInfo = _reflection.GeneratedProtocolMessageType('ErrorResourceInfo', (_message.Message,), dict(
  DESCRIPTOR = _ERRORRESOURCEINFO,
  __module__ = 'cmerror_data_pb2'
  # @@protoc_insertion_point(class_scope:ErrorResourceInfo)
  ))
_sym_db.RegisterMessage(ErrorResourceInfo)

CmerrorData = _reflection.GeneratedProtocolMessageType('CmerrorData', (_message.Message,), dict(
  DESCRIPTOR = _CMERRORDATA,
  __module__ = 'cmerror_data_pb2'
  # @@protoc_insertion_point(class_scope:CmerrorData)
  ))
_sym_db.RegisterMessage(CmerrorData)

jnpr_cmerror_data_ext.message_type = _CMERRORDATA
telemetry__top__pb2.JuniperNetworksSensors.RegisterExtension(jnpr_cmerror_data_ext)

_ERRORDATA.fields_by_name['identifier'].has_options = True
_ERRORDATA.fields_by_name['identifier']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\010\001'))
_ERRORDATA.fields_by_name['count'].has_options = True
_ERRORDATA.fields_by_name['count']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\030\001'))
_ERRORDATA.fields_by_name['last_updated'].has_options = True
_ERRORDATA.fields_by_name['last_updated']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\020\001'))
_ERRORDATA.fields_by_name['occur_count'].has_options = True
_ERRORDATA.fields_by_name['occur_count']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\030\001'))
_ERRORDATA.fields_by_name['cleared_count'].has_options = True
_ERRORDATA.fields_by_name['cleared_count']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\030\001'))
_ERRORDATA.fields_by_name['last_cleared_at'].has_options = True
_ERRORDATA.fields_by_name['last_cleared_at']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\020\001'))
_ERRORDATA.fields_by_name['action_count'].has_options = True
_ERRORDATA.fields_by_name['action_count']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\030\001'))
_ERRORDATA.fields_by_name['last_action_taken_at'].has_options = True
_ERRORDATA.fields_by_name['last_action_taken_at']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\020\001'))
try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
