# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: port_exp.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import telemetry_top_pb2 as telemetry__top__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='port_exp.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0eport_exp.proto\x1a\x13telemetry_top.proto\":\n\x08Port_exp\x12.\n\x12interfaceExp_stats\x18\x01 \x03(\x0b\x32\x12.InterfaceExpInfos\"J\n\x11InterfaceExpInfos\x12\x16\n\x07if_name\x18\x01 \x02(\tB\x05\x82@\x02\x08\x01\x12\x1d\n\x15if_operational_status\x18\x02 \x01(\t:B\n\x16jnpr_interface_exp_ext\x12\x17.JuniperNetworksSensors\x18\x12 \x01(\x0b\x32\t.Port_exp')
  ,
  dependencies=[telemetry__top__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


JNPR_INTERFACE_EXP_EXT_FIELD_NUMBER = 18
jnpr_interface_exp_ext = _descriptor.FieldDescriptor(
  name='jnpr_interface_exp_ext', full_name='jnpr_interface_exp_ext', index=0,
  number=18, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


_PORT_EXP = _descriptor.Descriptor(
  name='Port_exp',
  full_name='Port_exp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='interfaceExp_stats', full_name='Port_exp.interfaceExp_stats', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=97,
)


_INTERFACEEXPINFOS = _descriptor.Descriptor(
  name='InterfaceExpInfos',
  full_name='InterfaceExpInfos',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='if_name', full_name='InterfaceExpInfos.if_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\010\001'))),
    _descriptor.FieldDescriptor(
      name='if_operational_status', full_name='InterfaceExpInfos.if_operational_status', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=173,
)

_PORT_EXP.fields_by_name['interfaceExp_stats'].message_type = _INTERFACEEXPINFOS
DESCRIPTOR.message_types_by_name['Port_exp'] = _PORT_EXP
DESCRIPTOR.message_types_by_name['InterfaceExpInfos'] = _INTERFACEEXPINFOS
DESCRIPTOR.extensions_by_name['jnpr_interface_exp_ext'] = jnpr_interface_exp_ext

Port_exp = _reflection.GeneratedProtocolMessageType('Port_exp', (_message.Message,), dict(
  DESCRIPTOR = _PORT_EXP,
  __module__ = 'port_exp_pb2'
  # @@protoc_insertion_point(class_scope:Port_exp)
  ))
_sym_db.RegisterMessage(Port_exp)

InterfaceExpInfos = _reflection.GeneratedProtocolMessageType('InterfaceExpInfos', (_message.Message,), dict(
  DESCRIPTOR = _INTERFACEEXPINFOS,
  __module__ = 'port_exp_pb2'
  # @@protoc_insertion_point(class_scope:InterfaceExpInfos)
  ))
_sym_db.RegisterMessage(InterfaceExpInfos)

jnpr_interface_exp_ext.message_type = _PORT_EXP
telemetry__top__pb2.JuniperNetworksSensors.RegisterExtension(jnpr_interface_exp_ext)

_INTERFACEEXPINFOS.fields_by_name['if_name'].has_options = True
_INTERFACEEXPINFOS.fields_by_name['if_name']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\010\001'))
try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
