# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sr_stats_per_if_ingress.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import telemetry_top_pb2 as telemetry__top__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sr_stats_per_if_ingress.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x1dsr_stats_per_if_ingress.proto\x1a\x13telemetry_top.proto\"I\n\x13SrStatsPerIfIngress\x12\x32\n\x0eper_if_records\x18\x01 \x03(\x0b\x32\x1a.SegmentRoutingIngIfRecord\"\xd2\x01\n\x19SegmentRoutingIngIfRecord\x12\x16\n\x07if_name\x18\x01 \x02(\tB\x05\x82@\x02\x08\x01\x12\x1d\n\x0eparent_ae_name\x18\x02 \x01(\tB\x05\x82@\x02\x08\x01\x12\x1b\n\x0c\x63ounter_name\x18\x03 \x01(\tB\x05\x82@\x02\x08\x01\x12\x30\n\ringress_stats\x18\x04 \x01(\x0b\x32\x19.SegmentRoutingIngIfStats\x12/\n\x0c\x65gress_stats\x18\x05 \x01(\x0b\x32\x19.SegmentRoutingIngIfStats\"~\n\x18SegmentRoutingIngIfStats\x12\x16\n\x07packets\x18\x01 \x01(\x04\x42\x05\x82@\x02\x18\x01\x12\x14\n\x05\x62ytes\x18\x02 \x01(\x04\x42\x05\x82@\x02\x18\x01\x12\x1a\n\x0bpacket_rate\x18\x03 \x01(\x04\x42\x05\x82@\x02 \x01\x12\x18\n\tbyte_rate\x18\x04 \x01(\x04\x42\x05\x82@\x02 \x01:W\n jnpr_sr_stats_per_if_ingress_ext\x12\x17.JuniperNetworksSensors\x18\x13 \x01(\x0b\x32\x14.SrStatsPerIfIngress')
  ,
  dependencies=[telemetry__top__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


JNPR_SR_STATS_PER_IF_INGRESS_EXT_FIELD_NUMBER = 19
jnpr_sr_stats_per_if_ingress_ext = _descriptor.FieldDescriptor(
  name='jnpr_sr_stats_per_if_ingress_ext', full_name='jnpr_sr_stats_per_if_ingress_ext', index=0,
  number=19, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


_SRSTATSPERIFINGRESS = _descriptor.Descriptor(
  name='SrStatsPerIfIngress',
  full_name='SrStatsPerIfIngress',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='per_if_records', full_name='SrStatsPerIfIngress.per_if_records', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=127,
)


_SEGMENTROUTINGINGIFRECORD = _descriptor.Descriptor(
  name='SegmentRoutingIngIfRecord',
  full_name='SegmentRoutingIngIfRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='if_name', full_name='SegmentRoutingIngIfRecord.if_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\010\001'))),
    _descriptor.FieldDescriptor(
      name='parent_ae_name', full_name='SegmentRoutingIngIfRecord.parent_ae_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\010\001'))),
    _descriptor.FieldDescriptor(
      name='counter_name', full_name='SegmentRoutingIngIfRecord.counter_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\010\001'))),
    _descriptor.FieldDescriptor(
      name='ingress_stats', full_name='SegmentRoutingIngIfRecord.ingress_stats', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='egress_stats', full_name='SegmentRoutingIngIfRecord.egress_stats', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=340,
)


_SEGMENTROUTINGINGIFSTATS = _descriptor.Descriptor(
  name='SegmentRoutingIngIfStats',
  full_name='SegmentRoutingIngIfStats',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='packets', full_name='SegmentRoutingIngIfStats.packets', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\030\001'))),
    _descriptor.FieldDescriptor(
      name='bytes', full_name='SegmentRoutingIngIfStats.bytes', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\030\001'))),
    _descriptor.FieldDescriptor(
      name='packet_rate', full_name='SegmentRoutingIngIfStats.packet_rate', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002 \001'))),
    _descriptor.FieldDescriptor(
      name='byte_rate', full_name='SegmentRoutingIngIfStats.byte_rate', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002 \001'))),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=342,
  serialized_end=468,
)

_SRSTATSPERIFINGRESS.fields_by_name['per_if_records'].message_type = _SEGMENTROUTINGINGIFRECORD
_SEGMENTROUTINGINGIFRECORD.fields_by_name['ingress_stats'].message_type = _SEGMENTROUTINGINGIFSTATS
_SEGMENTROUTINGINGIFRECORD.fields_by_name['egress_stats'].message_type = _SEGMENTROUTINGINGIFSTATS
DESCRIPTOR.message_types_by_name['SrStatsPerIfIngress'] = _SRSTATSPERIFINGRESS
DESCRIPTOR.message_types_by_name['SegmentRoutingIngIfRecord'] = _SEGMENTROUTINGINGIFRECORD
DESCRIPTOR.message_types_by_name['SegmentRoutingIngIfStats'] = _SEGMENTROUTINGINGIFSTATS
DESCRIPTOR.extensions_by_name['jnpr_sr_stats_per_if_ingress_ext'] = jnpr_sr_stats_per_if_ingress_ext

SrStatsPerIfIngress = _reflection.GeneratedProtocolMessageType('SrStatsPerIfIngress', (_message.Message,), dict(
  DESCRIPTOR = _SRSTATSPERIFINGRESS,
  __module__ = 'sr_stats_per_if_ingress_pb2'
  # @@protoc_insertion_point(class_scope:SrStatsPerIfIngress)
  ))
_sym_db.RegisterMessage(SrStatsPerIfIngress)

SegmentRoutingIngIfRecord = _reflection.GeneratedProtocolMessageType('SegmentRoutingIngIfRecord', (_message.Message,), dict(
  DESCRIPTOR = _SEGMENTROUTINGINGIFRECORD,
  __module__ = 'sr_stats_per_if_ingress_pb2'
  # @@protoc_insertion_point(class_scope:SegmentRoutingIngIfRecord)
  ))
_sym_db.RegisterMessage(SegmentRoutingIngIfRecord)

SegmentRoutingIngIfStats = _reflection.GeneratedProtocolMessageType('SegmentRoutingIngIfStats', (_message.Message,), dict(
  DESCRIPTOR = _SEGMENTROUTINGINGIFSTATS,
  __module__ = 'sr_stats_per_if_ingress_pb2'
  # @@protoc_insertion_point(class_scope:SegmentRoutingIngIfStats)
  ))
_sym_db.RegisterMessage(SegmentRoutingIngIfStats)

jnpr_sr_stats_per_if_ingress_ext.message_type = _SRSTATSPERIFINGRESS
telemetry__top__pb2.JuniperNetworksSensors.RegisterExtension(jnpr_sr_stats_per_if_ingress_ext)

_SEGMENTROUTINGINGIFRECORD.fields_by_name['if_name'].has_options = True
_SEGMENTROUTINGINGIFRECORD.fields_by_name['if_name']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\010\001'))
_SEGMENTROUTINGINGIFRECORD.fields_by_name['parent_ae_name'].has_options = True
_SEGMENTROUTINGINGIFRECORD.fields_by_name['parent_ae_name']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\010\001'))
_SEGMENTROUTINGINGIFRECORD.fields_by_name['counter_name'].has_options = True
_SEGMENTROUTINGINGIFRECORD.fields_by_name['counter_name']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\010\001'))
_SEGMENTROUTINGINGIFSTATS.fields_by_name['packets'].has_options = True
_SEGMENTROUTINGINGIFSTATS.fields_by_name['packets']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\030\001'))
_SEGMENTROUTINGINGIFSTATS.fields_by_name['bytes'].has_options = True
_SEGMENTROUTINGINGIFSTATS.fields_by_name['bytes']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\030\001'))
_SEGMENTROUTINGINGIFSTATS.fields_by_name['packet_rate'].has_options = True
_SEGMENTROUTINGINGIFSTATS.fields_by_name['packet_rate']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002 \001'))
_SEGMENTROUTINGINGIFSTATS.fields_by_name['byte_rate'].has_options = True
_SEGMENTROUTINGINGIFSTATS.fields_by_name['byte_rate']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002 \001'))
try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
