# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: jnx_base_types.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='jnx_base_types.proto',
  package='jnxBase',
  syntax='proto3',
  serialized_pb=_b('\n\x14jnx_base_types.proto\x12\x07jnxBase\x1a google/protobuf/descriptor.proto\"*\n\x0cStrKeyStrVal\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"0\n\x07TimeVal\x12\x0f\n\x07seconds\x18\x01 \x01(\x04\x12\x14\n\x0cmicroseconds\x18\x02 \x01(\x04\"?\n\tRpcStatus\x12!\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x13.jnxBase.StatusCode\x12\x0f\n\x07message\x18\x02 \x01(\t*&\n\nStatusCode\x12\x0b\n\x07SUCCESS\x10\x00\x12\x0b\n\x07\x46\x41ILURE\x10\x01:4\n\x0cjapi_version\x12\x1c.google.protobuf.FileOptions\x18\xd0\x86\x03 \x01(\tb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_descriptor__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_STATUSCODE = _descriptor.EnumDescriptor(
  name='StatusCode',
  full_name='jnxBase.StatusCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FAILURE', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=226,
  serialized_end=264,
)
_sym_db.RegisterEnumDescriptor(_STATUSCODE)

StatusCode = enum_type_wrapper.EnumTypeWrapper(_STATUSCODE)
SUCCESS = 0
FAILURE = 1

JAPI_VERSION_FIELD_NUMBER = 50000
japi_version = _descriptor.FieldDescriptor(
  name='japi_version', full_name='jnxBase.japi_version', index=0,
  number=50000, type=9, cpp_type=9, label=1,
  has_default_value=False, default_value=_b("").decode('utf-8'),
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


_STRKEYSTRVAL = _descriptor.Descriptor(
  name='StrKeyStrVal',
  full_name='jnxBase.StrKeyStrVal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='jnxBase.StrKeyStrVal.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='jnxBase.StrKeyStrVal.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=109,
)


_TIMEVAL = _descriptor.Descriptor(
  name='TimeVal',
  full_name='jnxBase.TimeVal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='seconds', full_name='jnxBase.TimeVal.seconds', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='microseconds', full_name='jnxBase.TimeVal.microseconds', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=159,
)


_RPCSTATUS = _descriptor.Descriptor(
  name='RpcStatus',
  full_name='jnxBase.RpcStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='jnxBase.RpcStatus.code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message', full_name='jnxBase.RpcStatus.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=161,
  serialized_end=224,
)

_RPCSTATUS.fields_by_name['code'].enum_type = _STATUSCODE
DESCRIPTOR.message_types_by_name['StrKeyStrVal'] = _STRKEYSTRVAL
DESCRIPTOR.message_types_by_name['TimeVal'] = _TIMEVAL
DESCRIPTOR.message_types_by_name['RpcStatus'] = _RPCSTATUS
DESCRIPTOR.enum_types_by_name['StatusCode'] = _STATUSCODE
DESCRIPTOR.extensions_by_name['japi_version'] = japi_version

StrKeyStrVal = _reflection.GeneratedProtocolMessageType('StrKeyStrVal', (_message.Message,), dict(
  DESCRIPTOR = _STRKEYSTRVAL,
  __module__ = 'jnx_base_types_pb2'
  # @@protoc_insertion_point(class_scope:jnxBase.StrKeyStrVal)
  ))
_sym_db.RegisterMessage(StrKeyStrVal)

TimeVal = _reflection.GeneratedProtocolMessageType('TimeVal', (_message.Message,), dict(
  DESCRIPTOR = _TIMEVAL,
  __module__ = 'jnx_base_types_pb2'
  # @@protoc_insertion_point(class_scope:jnxBase.TimeVal)
  ))
_sym_db.RegisterMessage(TimeVal)

RpcStatus = _reflection.GeneratedProtocolMessageType('RpcStatus', (_message.Message,), dict(
  DESCRIPTOR = _RPCSTATUS,
  __module__ = 'jnx_base_types_pb2'
  # @@protoc_insertion_point(class_scope:jnxBase.RpcStatus)
  ))
_sym_db.RegisterMessage(RpcStatus)

google_dot_protobuf_dot_descriptor__pb2.FileOptions.RegisterExtension(japi_version)

try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
