# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sr_stats_per_sid.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import telemetry_top_pb2 as telemetry__top__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sr_stats_per_sid.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x16sr_stats_per_sid.proto\x1a\x13telemetry_top.proto\"9\n\rSrStatsPerSid\x12(\n\tsid_stats\x18\x01 \x03(\x0b\x32\x15.SegmentRoutingRecord\"\xcf\x01\n\x14SegmentRoutingRecord\x12\x1d\n\x0esid_identifier\x18\x01 \x02(\tB\x05\x82@\x02\x08\x01\x12\"\n\x13instance_identifier\x18\x02 \x01(\rB\x05\x82@\x02\x08\x01\x12\x1b\n\x0c\x63ounter_name\x18\x03 \x01(\tB\x05\x82@\x02\x08\x01\x12+\n\ringress_stats\x18\x04 \x01(\x0b\x32\x14.SegmentRoutingStats\x12*\n\x0c\x65gress_stats\x18\x05 \x01(\x0b\x32\x14.SegmentRoutingStats\"y\n\x13SegmentRoutingStats\x12\x16\n\x07packets\x18\x01 \x01(\x04\x42\x05\x82@\x02\x18\x01\x12\x14\n\x05\x62ytes\x18\x02 \x01(\x04\x42\x05\x82@\x02\x18\x01\x12\x1a\n\x0bpacket_rate\x18\x03 \x01(\x04\x42\x05\x82@\x02 \x01\x12\x18\n\tbyte_rate\x18\x04 \x01(\x04\x42\x05\x82@\x02 \x01:J\n\x19jnpr_sr_stats_per_sid_ext\x12\x17.JuniperNetworksSensors\x18\x10 \x01(\x0b\x32\x0e.SrStatsPerSid')
  ,
  dependencies=[telemetry__top__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


JNPR_SR_STATS_PER_SID_EXT_FIELD_NUMBER = 16
jnpr_sr_stats_per_sid_ext = _descriptor.FieldDescriptor(
  name='jnpr_sr_stats_per_sid_ext', full_name='jnpr_sr_stats_per_sid_ext', index=0,
  number=16, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


_SRSTATSPERSID = _descriptor.Descriptor(
  name='SrStatsPerSid',
  full_name='SrStatsPerSid',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sid_stats', full_name='SrStatsPerSid.sid_stats', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=104,
)


_SEGMENTROUTINGRECORD = _descriptor.Descriptor(
  name='SegmentRoutingRecord',
  full_name='SegmentRoutingRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sid_identifier', full_name='SegmentRoutingRecord.sid_identifier', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\010\001'))),
    _descriptor.FieldDescriptor(
      name='instance_identifier', full_name='SegmentRoutingRecord.instance_identifier', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\010\001'))),
    _descriptor.FieldDescriptor(
      name='counter_name', full_name='SegmentRoutingRecord.counter_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\010\001'))),
    _descriptor.FieldDescriptor(
      name='ingress_stats', full_name='SegmentRoutingRecord.ingress_stats', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='egress_stats', full_name='SegmentRoutingRecord.egress_stats', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=314,
)


_SEGMENTROUTINGSTATS = _descriptor.Descriptor(
  name='SegmentRoutingStats',
  full_name='SegmentRoutingStats',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='packets', full_name='SegmentRoutingStats.packets', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\030\001'))),
    _descriptor.FieldDescriptor(
      name='bytes', full_name='SegmentRoutingStats.bytes', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\030\001'))),
    _descriptor.FieldDescriptor(
      name='packet_rate', full_name='SegmentRoutingStats.packet_rate', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002 \001'))),
    _descriptor.FieldDescriptor(
      name='byte_rate', full_name='SegmentRoutingStats.byte_rate', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002 \001'))),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=316,
  serialized_end=437,
)

_SRSTATSPERSID.fields_by_name['sid_stats'].message_type = _SEGMENTROUTINGRECORD
_SEGMENTROUTINGRECORD.fields_by_name['ingress_stats'].message_type = _SEGMENTROUTINGSTATS
_SEGMENTROUTINGRECORD.fields_by_name['egress_stats'].message_type = _SEGMENTROUTINGSTATS
DESCRIPTOR.message_types_by_name['SrStatsPerSid'] = _SRSTATSPERSID
DESCRIPTOR.message_types_by_name['SegmentRoutingRecord'] = _SEGMENTROUTINGRECORD
DESCRIPTOR.message_types_by_name['SegmentRoutingStats'] = _SEGMENTROUTINGSTATS
DESCRIPTOR.extensions_by_name['jnpr_sr_stats_per_sid_ext'] = jnpr_sr_stats_per_sid_ext

SrStatsPerSid = _reflection.GeneratedProtocolMessageType('SrStatsPerSid', (_message.Message,), dict(
  DESCRIPTOR = _SRSTATSPERSID,
  __module__ = 'sr_stats_per_sid_pb2'
  # @@protoc_insertion_point(class_scope:SrStatsPerSid)
  ))
_sym_db.RegisterMessage(SrStatsPerSid)

SegmentRoutingRecord = _reflection.GeneratedProtocolMessageType('SegmentRoutingRecord', (_message.Message,), dict(
  DESCRIPTOR = _SEGMENTROUTINGRECORD,
  __module__ = 'sr_stats_per_sid_pb2'
  # @@protoc_insertion_point(class_scope:SegmentRoutingRecord)
  ))
_sym_db.RegisterMessage(SegmentRoutingRecord)

SegmentRoutingStats = _reflection.GeneratedProtocolMessageType('SegmentRoutingStats', (_message.Message,), dict(
  DESCRIPTOR = _SEGMENTROUTINGSTATS,
  __module__ = 'sr_stats_per_sid_pb2'
  # @@protoc_insertion_point(class_scope:SegmentRoutingStats)
  ))
_sym_db.RegisterMessage(SegmentRoutingStats)

jnpr_sr_stats_per_sid_ext.message_type = _SRSTATSPERSID
telemetry__top__pb2.JuniperNetworksSensors.RegisterExtension(jnpr_sr_stats_per_sid_ext)

_SEGMENTROUTINGRECORD.fields_by_name['sid_identifier'].has_options = True
_SEGMENTROUTINGRECORD.fields_by_name['sid_identifier']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\010\001'))
_SEGMENTROUTINGRECORD.fields_by_name['instance_identifier'].has_options = True
_SEGMENTROUTINGRECORD.fields_by_name['instance_identifier']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\010\001'))
_SEGMENTROUTINGRECORD.fields_by_name['counter_name'].has_options = True
_SEGMENTROUTINGRECORD.fields_by_name['counter_name']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\010\001'))
_SEGMENTROUTINGSTATS.fields_by_name['packets'].has_options = True
_SEGMENTROUTINGSTATS.fields_by_name['packets']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\030\001'))
_SEGMENTROUTINGSTATS.fields_by_name['bytes'].has_options = True
_SEGMENTROUTINGSTATS.fields_by_name['bytes']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\030\001'))
_SEGMENTROUTINGSTATS.fields_by_name['packet_rate'].has_options = True
_SEGMENTROUTINGSTATS.fields_by_name['packet_rate']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002 \001'))
_SEGMENTROUTINGSTATS.fields_by_name['byte_rate'].has_options = True
_SEGMENTROUTINGSTATS.fields_by_name['byte_rate']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002 \001'))
try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
