# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: jnx_authentication_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import jnx_common_base_types_pb2 as jnx__common__base__types__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='jnx_authentication_service.proto',
  package='jnx.jet.authentication',
  syntax='proto3',
  serialized_options=b'\202\265\030\0050.0.0\212\265\030\00418.4',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n jnx_authentication_service.proto\x12\x16jnx.jet.authentication\x1a\x1bjnx_common_base_types.proto\"E\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x11\n\tclient_id\x18\x03 \x01(\t\"J\n\rLoginResponse\x12)\n\x06status\x18\x01 \x01(\x0b\x32\x19.jnx.jet.common.RpcStatusJ\x04\x08\x02\x10\x03R\x08sub_code2h\n\x0e\x41uthentication\x12V\n\x05Login\x12$.jnx.jet.authentication.LoginRequest\x1a%.jnx.jet.authentication.LoginResponse\"\x00\x42\x11\x82\xb5\x18\x05\x30.0.0\x8a\xb5\x18\x04\x31\x38.4b\x06proto3'
  ,
  dependencies=[jnx__common__base__types__pb2.DESCRIPTOR,])




_LOGINREQUEST = _descriptor.Descriptor(
  name='LoginRequest',
  full_name='jnx.jet.authentication.LoginRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='jnx.jet.authentication.LoginRequest.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='password', full_name='jnx.jet.authentication.LoginRequest.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='client_id', full_name='jnx.jet.authentication.LoginRequest.client_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=158,
)


_LOGINRESPONSE = _descriptor.Descriptor(
  name='LoginResponse',
  full_name='jnx.jet.authentication.LoginResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='jnx.jet.authentication.LoginResponse.status', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=160,
  serialized_end=234,
)

_LOGINRESPONSE.fields_by_name['status'].message_type = jnx__common__base__types__pb2._RPCSTATUS
DESCRIPTOR.message_types_by_name['LoginRequest'] = _LOGINREQUEST
DESCRIPTOR.message_types_by_name['LoginResponse'] = _LOGINRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LoginRequest = _reflection.GeneratedProtocolMessageType('LoginRequest', (_message.Message,), {
  'DESCRIPTOR' : _LOGINREQUEST,
  '__module__' : 'jnx_authentication_service_pb2'
  # @@protoc_insertion_point(class_scope:jnx.jet.authentication.LoginRequest)
  })
_sym_db.RegisterMessage(LoginRequest)

LoginResponse = _reflection.GeneratedProtocolMessageType('LoginResponse', (_message.Message,), {
  'DESCRIPTOR' : _LOGINRESPONSE,
  '__module__' : 'jnx_authentication_service_pb2'
  # @@protoc_insertion_point(class_scope:jnx.jet.authentication.LoginResponse)
  })
_sym_db.RegisterMessage(LoginResponse)


DESCRIPTOR._options = None

_AUTHENTICATION = _descriptor.ServiceDescriptor(
  name='Authentication',
  full_name='jnx.jet.authentication.Authentication',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=236,
  serialized_end=340,
  methods=[
  _descriptor.MethodDescriptor(
    name='Login',
    full_name='jnx.jet.authentication.Authentication.Login',
    index=0,
    containing_service=None,
    input_type=_LOGINREQUEST,
    output_type=_LOGINRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_AUTHENTICATION)

DESCRIPTOR.services_by_name['Authentication'] = _AUTHENTICATION

# @@protoc_insertion_point(module_scope)
